### PR TITLE
lz - add facebook login/out

### PR DESCRIPTION
**Pull request by lzhang0616**

### CODE REVIEW

**Comment by ipmsteven** [comment]
why we need FB login?

**Comment by lzhang0616** [comment]
Later we can have user history with the user info grabbed from facebook.

**Comment by ipmsteven** [comment]
hmm, that means we will lose the user in GFW :(

**Comment by lzhang0616** [comment]
We won't require the log in before showing home page. The log in session will be optional as a navigation bar button... The root will be our index page. No mandatory login required.

**Pull request merged**
